export const PREFERRED_DEBUG_ORDER = [
  "open",
  "metadata_ready",
  "audio_pipeline_ready",
  "video_demux",
  "video_gop",
  "decoder_ready",
  "hw_decode_decision",
  "running",
  "first_frame",
  "color_profile",
  "video_integrity",
  "video_pipeline",
  "video_fps",
  "video_gap",
  "video_timestamps",
  "video_frame_types",
  "decode_cost_quantiles",
  "audio_stats",
  "audio_output",
  "av_sync",
  "audio_resume",
  "seek",
  "telemetry_timing",
  "telemetry_render",
  "telemetry_resources",
  "decode_error",
  "hw_decode_fallback",
] as const;

export const DEBUG_LABELS: Record<string, string> = {
  open: "打开",
  stream_start: "流启动",
  metadata_ready: "元数据就绪",
  audio_pipeline_ready: "音频管线就绪",
  decoder_ready: "解码器就绪",
  hw_decode_decision: "硬解决策",
  video_format: "视频格式",
  color_profile: "色彩配置",
  color_profill: "色彩配置",
  video_stream: "视频流",
  video_demux: "视频解复用",
  video_gop: "GOP/场景切换",
  video_timestamps: "时间戳质量",
  video_frame_types: "帧类型分布",
  decode_cost_quantiles: "耗时分位数",
  audio: "音频流",
  running: "播放状态",
  first_frame: "首帧就绪",
  video_pipeline: "视频管线",
  video_integrity: "视频完整性",
  telemetry_timing: "时序性能",
  telemetry_resources: "进程资源",
  telemetry_render: "渲染性能",
  video_fps: "视频帧率",
  audio_stats: "音频统计",
  audio_output: "音频输出",
  av_sync: "音视频同步",
  video_gap: "帧间间隔",
  seek: "跳转",
  audio_resume: "音频恢复",
  decode_error: "解码错误",
  hw_decode_fallback: "硬解回退",
  decode_error_detail: "解码错误细节",
  stop: "停止",
};

export const DEBUG_GROUP_ORDER = [
  "input",
  "stream",
  "decode",
  "video",
  "audio",
  "timing",
  "error",
  "other",
] as const;
