pub(crate) const MAX_EMIT_FPS: u32 = 60;
pub(crate) const METRICS_EMIT_INTERVAL_MS: u64 = 1000;
pub(crate) const AUDIO_ALLOWED_LEAD_SECONDS_DEFAULT: f64 = 0.008;
pub(crate) const AUDIO_ALLOWED_LEAD_SECONDS_DURING_SETTLE: f64 = 0.020;
pub(crate) const MAX_DECODE_LEAD_SECONDS_DEFAULT: f64 = 0.35;
pub(crate) const MAX_DECODE_LEAD_SECONDS_DURING_SETTLE: f64 = 0.55;
